version: '3'
services:
  php:
    entrypoint: php entrypoint.php
    build:
      context: .
      dockerfile: Dockerfile
    # auto-assign a name to the container
    container_name: not-a-bot
    # keep the container alive after invoked
    tty: true
    # for some reason you can't see the changed php code without running again the entrypoint.php, for now that's enough for me..
    # much quicker than having to destroy and reconstruct the image/container every time i change something
    volumes:
    - .:/usr/src/not-a-bot