version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    # auto-assign a name to the container
    container_name: not-a-bot
    # keep the container alive after invoked
    tty: true
    # TODO: find out why the live reloading is not working
    volumes:
    - ./:/usr/src/not-a-bot